name: Code Quality
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # all of code-quality actions are put together in a single job because of how github is rounding minutes for billing:
  # always to the whole minute, even if job is 2s long, see:
  # https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#:~:text=GitHub%2Dhosted%20runner.-,GitHub%20rounds,-the%20minutes%20and
  code-quality:
    name: lint & typecheck & triggering e2e tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/trigger-e2e
        with:
          PAT_TOKEN: ${{ secrets.ELEARNING_TESTING_PAT_TOKEN }}

      # lint & typecheck
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version-file: ".nvmrc"
      - run: pnpm install
      - run: pnpm --filter @frsource/frschool-elearning-web prepare
      - run: pnpm lint
      - run: pnpm typecheck:ci

  build-and-deploy-stage:
    needs: [code-quality]
    uses: ./.github/workflows/deploy-stage.yml
    secrets: inherit
    with:
      skip-deploy: ${{ github.event_name != 'push' || github.actor == 'renovate[bot]' }}
      DATABASE_USER: ${{ vars.ELEARNING_STAGE_DATABASE_USER }}
      DATABASE_NAME: ${{ vars.ELEARNING_STAGE_DATABASE_NAME }}
      EMAIL_HOST: ${{ vars.ELEARNING_API_EMAIL_HOST }}
      EMAIL_PASS: ${{ vars.ELEARNING_API_EMAIL_PASS }}
      EMAIL_PORT: ${{ vars.ELEARNING_API_EMAIL_PORT }}
      EMAIL_USER: ${{ vars.ELEARNING_API_EMAIL_USER }}
